version: '3.8'

services:
  yii2-app:
    image: IMAGE_TAG
    ports:
      - "9090:9090"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - app-data:/var/www/html

volumes:
  app-data:
