version: '3.8'

services:
  yii2-app:
    image: IMAGE_TAG
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
