version: '3.8'

services:
  yii2-app:
    image: IMAGE_TAG
    ports:
      - "9090:9090"
    networks:
      - yii2_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: ["php", "yii", "serve", "0.0.0.0", "--port=9090"]

networks:
  yii2_network:
    driver: overlay
