version: '3.8'

services:
  yii2-app:
    build: .
    container_name: yii2-app
    ports:
      - "9090:9090"
    volumes:
      - .:/var/www/html
    networks:
      - yii2_network
    command: ["php", "yii", "serve", "0.0.0.0", "--port=9090"]

networks:
  yii2_network:
    driver: bridge