name: Yii 2 CICD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CODE CHECKOUT
        uses: actions/checkout@v4

      - name: SSH into EC2 and echo message
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello, I'm from inside the EC2 instance!"

            # # CLONE & PULL THE PROJECT
            if [ -d "/home/ec2-user/yii2-deployment" ]; then
              echo "Project already cloned, pulling latest changes..."
              sudo chown -R ec2-user:ec2-user /home/ec2-user/yii2-deployment
              sudo chmod -R 755 /home/ec2-user/yii2-deployment
              cd /home/ec2-user/yii2-deployment && git pull
            else
              echo "Project directory doesn't exist, cloning repository..."
              git clone https://github.com/RameshXT/yii2-deployment.git /home/ec2-user/yii2-deployment
            fi


            # # DOCKER LOGIN
             docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


            # # BUILD DOCKER IMAGE
            docker build -t yii2-app:latest /home/ec2-user/yii2-deployment