name: CI/CD for EC2 Deployment

on:
  push:
    branches:
      - master  # Trigger this on push to the master branch (you can change this as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Step 3: Clean up EC2 Docker containers and images
    - name: Clean up containers and images
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          # Stop and remove all running containers
          CONTAINERS=$(docker ps -aq)
          if [ ! -z "$CONTAINERS" ]; then
            docker stop $CONTAINERS
            docker rm -f $CONTAINERS
          fi

          # Remove all Docker images
          IMAGES=$(docker images -aq)
          if [ ! -z "$IMAGES" ]; then
            docker rmi -f $IMAGES
          fi
        EOF

    # Step 4: Pull changes from GitHub
    - name: Pull changes from GitHub
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/yii2-deployment || exit 0
          git pull origin master
        EOF

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/yii2-deployment || exit 0
          docker build -t yii2 .
        EOF

    # Step 6: Run the Docker container
    - name: Run Docker container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          docker run -d -p 8080:8080 --name yii2 yii2
        EOF

    # Step 7: Get container logs
    - name: Get container logs
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          docker logs -f $(docker ps -q -f name=yii2)
        EOF
