name: Medusa CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CODE CHECKOUT
        uses: actions/checkout@v2

      - name: SET UP DOCKER BUILDx
        uses: docker/setup-buildx-action@v3

      - name: LOGIN DOCKER HUB
        run: |
          echo "Logging into Docker Hub.."
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Logged in to Docker Hub."

      - name: BUILD DOCKER IMAGE
        run: |
          IMAGE_TAG="rameshxt/yii2:v1.0.${GITHUB_RUN_NUMBER}"
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          echo "Image build complete."

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Starting to clean up and deploy..."
      
            # Step 1: Force delete all running containers
            CONTAINERS=$(docker ps -aq)
            if [ ! -z "$CONTAINERS" ]; then
              echo "Stopping and removing containers..."
              docker stop $CONTAINERS
              docker rm -f $CONTAINERS
            else
              echo "No containers to remove."
            fi
      
            # Step 2: Force delete all Docker images
            IMAGES=$(docker images -aq)
            if [ ! -z "$IMAGES" ]; then
              echo "Removing Docker images..."
              docker rmi -f $IMAGES
            else
              echo "No images to remove."
            fi
      
            # Step 3: Run the new Docker container
            IMAGE_TAG="${{ steps.build_and_deploy.outputs.image_tag }}"  # Dynamically reference the image tag here
            echo "Running the new Docker container with image: $IMAGE_TAG"
            if [ -z "$IMAGE_TAG" ]; then
              echo "ERROR: IMAGE_TAG is empty"
              exit 1
            fi
            docker run -d -p 8080:8080 --name yii2-container $IMAGE_TAG
            docker logs -f $(docker ps -q -f name=yii2)
