name: CI/CD for EC2 Deployment

on:
  push:
    branches:
      - main  # Trigger this on push to main branch (you can change this as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: CleanUp
      run: |
        docker stop $(docker ps -aq) && docker rm -f $(docker ps -aq) && docker rmi -f $(docker images -aq) 

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t yii2 /home/ec2-user/yii2-deployment

    # Step 4: SSH into EC2, stop and remove all containers, remove images, then run the new container
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          
          # Build and run the new Docker container
          docker build -t yii2 .
          docker run -d -p 8080:8080 yii2
          
          # Optional: Tail logs to verify the container is running
          docker logs -f $(docker ps -q -f name=yii2)
        EOF

    # Step 5: Capture logs (optional)
    - name: Get container logs
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} 'docker logs $(docker ps -q -f name=yii2)'
