name: Yii 2 CICD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CODE CHECKOUT
        uses: actions/checkout@v4

      - name: SSH into EC2 and echo message
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello, I'm from inside the EC2 instance!"
