name: CICD - Yii 2 Application

on:
  push:
    branches: [ master ]

jobs:
  CICD:
    name: Continuous Integration and Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ANSIBLE Configuration step
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 52.90.84.16 >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbooks/playbook.yml -i ansible/playbooks/hosts
