name: CICD - Yii 2 Application

on:
  push:
    branches: [ master ]

jobs:
  CICD:
    name: Continuous Integration and Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Ansible Configuration step 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ secrets.EC2_IP }}" >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbooks/configuration.yml -i ansible/playbooks/hosts

      # Docker Build Push steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: |
          echo "Logging into Docker Hub.."
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Logged in to Docker Hub."

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rameshxt/yii2:v2.0.${{ github.run_number }}
      
      